Bucharest hasn't seen for long such a thrilling atmosphere , with hundreds of thousands of people from all over the country gathered on the capital city 's roadsides . 
the first time arrival of a Pope in Bucharest and in a mainly Orthodox country deeply moved everybody to an extent we have seldom experineced before . 
leaving aside the importance of the visit , the most surprising fact is that Romanians look good when they are filled with joy . 
they radiate a kind of inner warmth that I ' m sure only few foreigners weren't able to perceive . 
the second fact that 's worth being highlighted is that the Pope 's visit to Romania has brought us a breath of European air and made us feel we were no longer a closed and isolated country at Europe 's outskirts . 
Bucharest and other cities a cross the country have lately hosted all sorts of international meetings , though they are still small in number , heads of states have come over to Romania , and now the illustrious Pope John Paul II is visiting our country . 
for the first time at an official ceremony , the bread and salt offered to welcome a guest didn't seem formal and the young people in national costumes didn't look as if they had been compelled to attend the ceremony . 
i ' m also sure that the millions of Romanians who watched the Pope 's arrival on TV left aside their daily hardships for some minutes or hours and went through emotions words can hardly depict . 
the truth is only few Romanians were not impressed with the visit by a great world personality such as Pope John Paul II to an Orthodox country , that takes place at this very tense moment sparked by the war in Yugoslavia . 
this ecumenical trip opens a new era to the dialogue between the Orthodox and Catholic churches . 
moreover , the talks held these three days will represent a step ahead in settling their disputes over the two churches ' properties . 
as for the Romanian Orthodox Church , often regarded as outdated and isolated , the meeting with Pope John Paul II here , in its very heart , is the clearest proof of its openness and desire of renewal . 
but the Pope 's visit to Bucharest isn't important only to Romania . 
the schism occurred in 1054 is still actual in an Europe no longer divided by as little as the Berlin wall . 
the religious division can place some obstacles to the continent 's integration trend . 
from this point of view , the Pope 's visit can contribute to the creation of a new type of relations between the eastern Europe and the West . 
for almost a millennium , the ecumenic move has tried to bridge the gap generated by the schism , without making significant headway . 
the Pope 's express wish to visit Romania , that is a mainly Orthodox country , can also be considered as a sign that soon the two Christian churches can come to a harmonious relationship as never before over the last millennium . 
for two decades , Pope John Paul II has been a messenger of peace a cross the world , and one of the most ardent supporters of dialogue between religions . 
after innumerable trips a cross the world , he came to Romania carrying the burden of his age and of his mission . 
shivering and with his shoulders drooping , speaking in a voice that radiates warmth and kindness , His Sanctity shyly stepped on Romania 's soil with an innocent child 's look in his eyes . 
the devotion he shows in his attempt to get familiar with a country and to lay the foundation for the Christians ' reconciliation is the most wonderful example of generosity . 
because the Orthodox and the Catholics are but Christians who failed to grasp the ultimate essence of the unique message conveyed by Jesus Christ and whom the troubled times caused to split up . 
yesterday , for the first time they felt closer to each other and ready for a reconciliation our ancestors had long stopped dreaming of . 
the image of Patriarch Teoctist by Pope John Paul II side in the pontiff 's vehicle is a historic picture that will be shown around the world . 
in fact , the Pope 's visit broadcast by a lot of television stations and expected to be watched by one billion people will greatly improve the image of Romania seen by many as some strange outskirts of the world . 
and we can really be proud that these days we have been a pole of Christianity . 
the joy yesterday was a moment of deliverance from the sufferings endured by Romanians for decades . 
it was as if the flickering light in everybody 's soul had joined to light up the whole country . 
