we need one more day in order to be able to assess the outcome of the local polls . 
but even before the announcement of the final ballot counting , we could survey the situation of the candidates who won only small percentages of the votes , without fearing that we might be wrong . 
considering that the partial counting of the ballots released by press agencies shows that the Rightist Force Union ( with 5.71 % of the votes in Bucharest ) and the National Liberal Party ( with 4.22 % of the votes ) hold the bottom positions ahead of the " and so on " and " et cetera " category of candidates who won less than 4 % of the votes , we can reach some conclusions that might remain final . 
he who was big will get little in no time . 
some months ago , many said that George Padure whose various opinion poll ratings were high would stand chances of becoming Bucharest general mayor . 
he displayed the gilded image of a businessman ( superimposed on a shallow reality ) and he was perceived as an outspoken guy pushing his way to the front and making all sorts of theatrical moves . 
where 's Padure now ? 
he ranks fourth with about 6 - 7 % of the votes . 
which makes us believe he was voted by gullible people and that he also induced sort of a disappointment with the National Liberal Party ( PNL ) whose councillors barely won 5 % of the votes . 
the National Liberal Party dropped in the Bucharest local polls to a dangerously low percentage . 
and it isn't only the infelicitous nomination of George Padure as candidate for the Bucharest mayor , but also some other things we ' ll dwell on soon that account for their drop . 
behind PNL there 's sort of a desert . 
the Alliance for Romania ( ApR ) anonymity was the most surprising . 
Mihai Erbasu was rather sort of an anticandidate . 
as a construction man , Erbasu doesn't know to play politics and election campaign . 
the few election posters and banners scattered a cross Bucharest couldn't possibly help him much . 
in a certain way this was an expectable result . 
most people imagined the party headed by Teodor Melescanu would see a considerable raise in its ratings . 
but it seems not only in the capital city polls the Alliance for Romania party suffered a defeat that could be triggered only by Costea scandal . 
the Romanian National Unity Party ( PUNR ) falls under the same category of " and so on " . 
Valeriu Tabara 's party was pulled the carpet from under its feet both in Cluj and in Bucharest and Tirgu Mures . 
the Greater Romania Party takes the place of PUNR in the places where there 's still something of the spirit that generated the latter . 
PUNR Iulian Cretu 's nomination for Bucharest mayor candidate is another note of the swan song . 
nor is Alexandru Athanasiu 's party doing well without the alliance called the Social Democratic Union . 
this party too shows signs of having shrunk , which announces tough times for it in the general elections . 
the Romanian Humanist Party has set a rule . 
the rule of a party that doesn't exist , but makes a lot of fuss and noise , enters alliances and pretends to deal the cards . 
the Romanian National Party ( PNR ) headed by former intelligence service head Virgil Magureanu is pretty much in the same situation . 
PNR stirs a lot of agitation through its head 's statements and televised apparitions . 
but in the local elections it fell under the " et cetera " class . 
many people looked with a certain curiosity the New Generation Party headed by current Bucharest mayor Viorel Lis , the Popular Party in Romania headed by former prime minister Radu Vasile and the National Christian Democratic Alliance headed by former prime minister Victor Ciorbea . 
it 's about three parties recently set up . 
they were set up based on their founders ' belief that they are well known , popular guys people are fond of , and therefore convinced that by breaking a way with the parties they fell they no longer belonged with they would gain deserved recognition . 
but they were totally wrong . 
i bet those counting the ballots got their fingers black with ink before spotting a ballot paper with the name of one of these parties ' candidates stamped . 
I don't mean to be rude and say we are dealing with false parties lacking substance , platforms and structure . 
or to say that in fact they don't count , despite their legal existence . 
the failure of the three parties in the local elections shows us how difficult it is to make up an important party . 
a man is just not enough to complete the task . 
you should create a structure , identify a need , and then skillfully promote the solution . 
Viorel Lis , Radu Vasile and Victor Ciorbea experienced their first big shock in their political life based on the illusions generated by their having been in power . 
maybe others too will learn something from this painful lesson . 
and as they also indulged in illusions , we should mention Marcian Bleahu , Ioan Popescu Rusavat , Mihai Barbuliceanu , Mihai Cornel Marmara , Paul Daniel Mircescu and Pavel Corut when speaking of the " and so on " chapter . 
they can say they ran in elections , got a mark beside their names in connection with their former political police past and they will return to their anonymous parties that are just fit to undergo revamping . 
