not even low grades can stand the form master reading them a lecture . 
they start fretting , whispering and looking up the walls . 
Scolding , lecturing , reading sermons are another words for boring somebody . 
modern pedagogy has identified ways to help people discover for themselves logical , necessary and obligatory conclusions . 
the technique comes from Socrates ' maieutic ( a method of gaining knowledge by a series of questions and answers ) and it still holds good with all the extensive subsequent research on the matter . 
but what 's to be done when this method has to be applied to millions of people ? 
the removal of the behavioral patterns imposed by the communist ideology has brought the masses unrestricted civil liberties . 
there are no rules and patterns any more . 
and in their absence people can become ugglier than under the threat of being whipped in to line . 
and it is only when living in a free world that some people will show how hideous they are . 
all these came to my mind when I heard about the gas pipe in the port town of Constanta punctured by thieves . 
for I don't know how many gas canisters worth two , three or ten million lei at most , some people ( it 's no point in calling them scums , it would sound like a lecture given by some class master ) wasted tens of tons of fuel . 
suppose we admit the damage isn't that big . 
they will be apprehended by police and forced to pay for the stolen gas , plus the gas leaked in to the ground during their operation , plus the pipe repair costs . 
obviously , the people who did that are not rich . 
they surely are part of those who bear the brunt of transition . 
they resorted to this very complicated operation as they were penniless . 
they took the risk of being caught or of getting killed in a blow up just to cover their needs for a week or two . 
is this destruction tolerable just because it was generated by poverty and despair ? 
some may say it is . 
they may say the state and the politicians should create an economic and social climate to allow everybody earn their living so they won't steal gas , hens , cars or money any more . 
which is too much to be done in such a short time . 
accomplishing all this takes time . 
and wisdom , above all . 
but it isn't only the rulers that need wisdom , it is also those who expect their life to change for the better . 
if the neurons in the brains of the poor don't work right , none of the ideas that should drive us to finally see the fruit of change will ever get implanted . 
and the stealing of cables from power lines , of pipes from the irrigation system , of gas from gas ducts , of relay switches from industrial power systems is a way of deluding ourselves , let alone the fact that it has turned in to a national sport . 
in Constanta , besides the stolen and wasted gas , tens of hectares of farming land have been wrecked . 
who cares that for many years from now on nothing will ever grow on that land ? ! 
we ' ll feed on what comes from air and water ! 
but these too are being polluted with all sorts of substances and involve growing danger to our lives ! 
to destroy forests , rivers and the air for nothing is tantamount to choosing to die behind the wheel of your car rather than allowing a car that has the right of way to go first . 
it 's the same old dose of irresponsibility we have to deal with each and every day , each and every hour . 
it 's the sign of a primitive way of thinking , though primitive thinking too was based on some symbols and some collective life rules . 
the vanishing of the communal spirit has generated these destructive impulse . 
how will we be able to restrain this destructive force and irrationality ? 
how can we make our fellow countrymen think twice and not ignore their fellow humans when they plan to do something that may cause damages to the whole community ? 
what should we do , hold classes to lecture them ? 
hold a session to read a sermon to the nation ? 
should we go back to use the whip ? 
a solution must be worked out , but that solution is not among the above - mentioned . 
we should go back to Socrates ' maieutic . 
to dialogue , communication , and to respect our fellow countrymen . 
Romania 's going back on a sound track implies that everybody should show a bit of wisdom . 
this can't come from the Americans , from the Germans or from the Martians . 
we ' ll get this supplementary drop of wisdom only if we don't spare our neurons . 
