Corneliu Vadim Tudor , the bin Laden of Romanian politics , is expected today before the Senate 's judiciary committee for explanations . 
it 's a procedure that precedes the next week 's debate by the full Senate when the removal of his parliamentary privilege is to be discussed . 
Vadim shows the lack of concern of an intangible man , though behind his pompous statements one can see his pants trembling on him . 
not because his case will be debated by the judiciary committee or the full Senate . 
he 's been there before . 
the PSD Standing Delegation is the cause behind Vadim 's serious fear . 
the day before yesterday , the top figures of the ruling party joined to discuss about the Vadim case . 
do you imagine Adrian Nastase 's party had doubts about what they have to do ? 
nothing of the sort ! 
they needed no debates or clarifying talks . 
but then why did they call the Standing Delegation to deal with the issue ? 
the answer is very simple . 
in the absence of a unanimously - made decision by the above - mentioned body , some MPs may vote according to their own conscience at the Senate 's debates . 
that is , in favour of Vadim Tudor and implicitly against the removal of his parliamentary privilege . 
in order to avoid such an unfortunate situation , Adrian Nastase resorted to a political trick . 
he called a meeting of the Standing Delegation and raised for discussion the party 's stand on the matter in question . 
were there any party men ready to defend Vadim ? 
though in private many of the PSD senior members do think exactly like the Greater Romania Party 's president , they kept their mouths shut before the party leadership . 
and considering they couldn't afford the luxury of speaking their minds and the decision was voted unanimously , it 's sure at the full Senate 's meeting they won't vote otherwise than what the Standing Delegation has decided . 
all these reasons make us believe this time the Social Democratic Party ( PSD ) has made a final decision in Vadim case . 
there are no elections coming to allow the hot - headed politician to escape justice , and there is no other party to obstruct the move . 
what would Vadim being pushed in to the justice claws imply ? 
beyond being a piece of news that is going to spark endless comments , teaching the president of the Greater Romania Romania Party ( PRM ) to know his place by using the instruments offered by democracy and the rule - of - law state would have pretty important consequences . 
a successful operation would bring PSD an European aura of a party capable to fight extremism and nationalism . 
a failure would be fatal not only to the ruling party , but also to the country . 
you can imagine that all the debates around the removal of Vadim 's parliamentary privilege and his being brought before justice will bring him an enormous exposure . 
besides the discontent of the disadvantaged social groups generated by the hardships they have to face , he could win over the disgruntled PSD members . 
that would be a real disaster . 
the attempt to teach Vadim a lesson could result in a huge political victory , but also in a disaster of huge proportions . 
the Social Democratic Party has unanimously launched an operation against a con - sanguine fellow . 
we ' ll either see the enforcement of the law or the worst thing possible . 
an incest ! 
