it 's easy to laugh about what happens to Greater Romania Party head Corneliu Vadim Tudor . 
he 's getting what he deserves . 
his party looks like a big truck loaded in the wrong way . 
all falls off that isn't firmly fastened in place . 
at every bump on the road , jerky movement or attempt made by some self - interested individual one more piece disappears from this incoherent political construction . 
what should we do if half of the Greater Romania Party ( PRM ) goes to blazes ? 
should we keep on laughing ? 
in my opinion , we can't let things slide . 
no matter how much Vadim deserves that and no matter how good the thinning of a party such as PRM may look , we can't overlook the implications of the move . 
I mean the migration of MPs after having been elected by voters . 
it 's not the first time when such a phenomenon occurs . 
it also happened in the previous legislatures . 
I think that in times of trouble , the same migration could occur in other parties , including the ruling party PSD which at present is in a great shape swallowing little fish from its rivals . 
the sure thing is the voters ' will is bent by behind - the - stage debates . 
the second extremely important issue has to do with the condition of the ruling party itself . 
does it have the moral right to take in anybody anyhow ? 
my opinion is that the " swallowing " of MPs in bulk doesn't bring too many advantages to a party that is already faced with enough identity and credibility problems . 
what will PSD be with some 20 - 30 PRM MPs among its members ? 
sort of PSDRM . 
it 's easy to notice the " blood type " is the same , as it was identified at the time of the " red quadrilateral " . 
only that for quite a while , Adrian Nastase 's party has been making visible efforts to move a way from that area . 
the party 's escutcheon , built with difficulty and still unfinished as it is , has rather to lose than to gain . 
as for Victor Hrebenciuc 's promise that the latest two " defectors " Ilie Neacsu and Sever Mesca will keep their current offices , it seems it was made on the spur of the moment when everybody was rubbing their hands with joy and before it was " processed " by the brain . 
i mean , do Adrian Nastase and Viorel Hrebenciuc think the party is richer now that it has an anti - Semite journalist and a former political police officer on its member list ? 
Vadim had no choice but to give a bogus journalist the office of chairman of the agriculture committee as he was faced with a shortage of men , but such a move by PSD is intolerable . 
the Romanian agriculture is already at a stalemate generated by confuse strategy . 
does PSd want to convince us now that keeping Ilie Neacsu on the agriculture committee is a solution benefitting both the farming sector and the party 's image abroad ? 
it 's an uninspired measure , not to say a big foolish thing . 
though foreigners may fail to notice that one of the anti - Semite hotheads in post - Ceausescu Romania is the chairman of a committee under the Chamber of Deputies , in my opinion we , Romanians , can't tolerate such an offense . 
we 're talking of a key sector in Romanian economy , where things go ever worse . 
as for Sever Mesca , PSD doesn't have many reasons for discontent or for being afraid that he will be perceived in a wrong way . 
the party had former Securitate officers among its members even before the arrival of the " defector " . 
Mesca 's joining the party will only result in a change in their number . 
the number of former Securitate officers is going down in PRM and up in PSD . 
do you know what happens to a whale after stuffing itself with food ? 
its moves slow down and it can't flap its tail any more . 
